# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20161217_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
